language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install .
    - pip install nose
    - pip install coveralls
script: nosetests --with-coverage --cover-package anywhere
after_success: coveralls
