language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install .
    - pip install ipykernel
    - pip install nose
    - pip install coveralls
script: nosetests --with-coverage --cover-package nbexec
after_success: coveralls
